name: Simulation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: lfenergy/arras:develop
    
    steps:
    - uses: actions/checkout@v3

    - name: Run simulation
      run: gridlabd main.glm

    - name: Save voltage profile
      uses: actions/upload-artifact@v3
      with:
        name: Voltage profile
        path: voltage-profile.png

    - name: Save JSON model
      uses: actions/upload-artifact@v3
      with:
        name: JSON model
        path: gridlabd.json
